export const products = [
    {
        id: 1,
        title: "Buzo UO",
        price: 10000,
        stock: 50,
        description: "Buzo negro canguro",
        category: "buzos",
        img: "https://res.cloudinary.com/dwavbmsb2/image/upload/v1682523546/urbanfrontbuzo-removebg-preview_fekyvo.png",
    },
    {
        id: 2,
        title: "Remera UO",
        price: 7000,
        stock: 100,
        description: "Remera negra con logo",
        category: "remeras",
        img: "https://res.cloudinary.com/dwavbmsb2/image/upload/v1682523608/urban1front-removebg-preview_a65ysd.png",
    },
    {
        id: 3,
        title: "Pantalon UO",
        price: 5000,
        stock: 30,
        description: "Pantalon negro con logo",
        category: "pantalones",
        img: "https://res.cloudinary.com/dwavbmsb2/image/upload/v1682523657/urbanpantder-removebg-preview_s0h3sn.png",
    },
    {
        id: 4,
        title: "Pantalon UO",
        price: 5000,
        stock: 30,
        description: "Pantalon negro con logo",
        category: "pantalones",
        img: "https://res.cloudinary.com/dwavbmsb2/image/upload/v1682523955/urbanpantizq-removebg-preview_bka2lr.png",
    },
    {
        id: 5,
        title: "Buzo UO",
        price: 10000,
        stock: 30,
        description: "Buzo negro con logo",
        category: "buzos",
        img: "https://res.cloudinary.com/dwavbmsb2/image/upload/v1682524060/urbansidebuzo-removebg-preview_alermn.png",
    },
    {
        id: 6,
        title: "Remera UO",
        price: 7000,
        stock: 30,
        description: "Remera negro con logo",
        category: "remeras",
        img: "https://res.cloudinary.com/dwavbmsb2/image/upload/v1682524059/urban1-removebg-preview_nh3b0u.png",
    },
    {
        id: 7,
        title: "Pantalon UO",
        price: 5000,
        stock: 30,
        description: "Pantalon negro con logo",
        category: "pantalones",
        img: "https://res.cloudinary.com/dwavbmsb2/image/upload/v1682523657/urbanpantder-removebg-preview_s0h3sn.png",
    },
    {
        id: 8,
        title: "Pantalon UO",
        price: 5000,
        stock: 30,
        description: "Pantalon negro con logo",
        category: "pantalones",
        img: "https://res.cloudinary.com/dwavbmsb2/image/upload/v1682523657/urbanpantder-removebg-preview_s0h3sn.png",
    },
];
